const customStyles = {
    root: {
        fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", "Helvetica Neue", Helvetica, Arial, sans-serif',
    },
    body: {
        background: '#000',
        backgroundImage: `
      radial-gradient(ellipse at top left, rgba(45, 35, 80, 0.6), transparent 50%),
      radial-gradient(ellipse at bottom right, rgba(20, 50, 70, 0.5), transparent 50%),
      radial-gradient(circle at 50% 50%, rgba(20, 20, 25, 1), #050505 100%)
    `,
        backgroundAttachment: 'fixed',
        minHeight: '100vh',
        display: 'flex',
        overflow: 'hidden',
        WebkitFontSmoothing: 'antialiased',
        MozOsxFontSmoothing: 'grayscale',
        color: '#FFFFFF',
    },
    glassPanel: {
        background: 'rgba(30, 30, 32, 0.45)',
        backdropFilter: 'blur(40px)',
        WebkitBackdropFilter: 'blur(40px)',
        border: '1px solid rgba(255, 255, 255, 0.12)',
        boxShadow: '0 10px 40px -10px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255, 255, 255, 0.1)',
    },
    appContainer: {
        display: 'flex',
        width: '100%',
        height: '100vh',
        padding: '16px',
        gap: '20px',
    },
    sidebar: {
        width: '260px',
        flexShrink: 0,
        borderRadius: '28px',
        display: 'flex',
        flexDirection: 'column',
        padding: '24px 16px',
    },
    brand: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '0 12px 32px 12px',
        fontWeight: 600,
        fontSize: '18px',
        letterSpacing: '-0.2px',
    },
    navSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        marginBottom: '24px',
    },
    navLabel: {
        fontSize: '11px',
        textTransform: 'uppercase',
        letterSpacing: '0.8px',
        color: 'rgba(255, 255, 255, 0.55)',
        padding: '0 12px 8px 12px',
        fontWeight: 500,
    },
    navItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '14px',
        padding: '10px 12px',
        borderRadius: '14px',
        cursor: 'pointer',
        transition: 'background 0.2s ease',
        textDecoration: 'none',
        color: '#FFFFFF',
        fontSize: '15px',
        fontWeight: 400,
        letterSpacing: '-0.1px',
    },
    navItemActive: {
        background: 'rgba(255, 255, 255, 0.15)',
    },
    navItemHover: {
        background: 'rgba(255, 255, 255, 0.1)',
    },
    mainContent: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        overflowY: 'auto',
        paddingRight: '8px',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '8px 0',
    },
    pageTitle: {
        fontSize: '28px',
        fontWeight: 600,
        letterSpacing: '-0.5px',
    },
    userProfile: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '6px 16px 6px 6px',
        borderRadius: '28px',
        background: 'rgba(255, 255, 255, 0.08)',
        border: '1px solid rgba(255, 255, 255, 0.12)',
        cursor: 'pointer',
        transition: 'background 0.2s',
    },
    avatar: {
        width: '32px',
        height: '32px',
        borderRadius: '50%',
        background: 'linear-gradient(135deg, #a8c0ff, #3f2b96)',
    },
    userName: {
        fontSize: '14px',
        fontWeight: 500,
    },
    dashboardGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: '20px',
    },
    card: {
        borderRadius: '20px',
        padding: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        position: 'relative',
        overflow: 'hidden',
    },
    kpiHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        color: 'rgba(255, 255, 255, 0.55)',
    },
    kpiTitle: {
        fontSize: '13px',
        fontWeight: 500,
    },
    kpiIcon: {
        width: '24px',
        height: '24px',
        borderRadius: '8px',
        background: 'rgba(255, 255, 255, 0.08)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        border: '1px solid rgba(255,255,255,0.05)',
    },
    kpiValue: {
        fontSize: '32px',
        fontWeight: 600,
        letterSpacing: '-1px',
        marginTop: '4px',
    },
    kpiTrend: {
        fontSize: '13px',
        fontWeight: 500,
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
    },
    trendUp: { color: '#32D74B' },
    trendDown: { color: '#FF453A' },
    analyticsRow: {
        display: 'grid',
        gridTemplateColumns: '2fr 1fr',
        gap: '20px',
    },
    sectionTitle: {
        fontSize: '16px',
        fontWeight: 600,
        marginBottom: '20px',
        letterSpacing: '-0.2px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    actionLink: {
        fontSize: '13px',
        color: 'rgba(255, 255, 255, 0.55)',
        textDecoration: 'none',
        fontWeight: 400,
        cursor: 'pointer',
        transition: 'color 0.2s',
    },
    chartContainer: {
        height: '220px',
        width: '100%',
        position: 'relative',
        display: 'flex',
        alignItems: 'flex-end',
        paddingBottom: '20px',
        paddingLeft: '30px',
    },
    yAxis: {
        position: 'absolute',
        left: 0,
        top: 0,
        height: 'calc(100% - 20px)',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        fontSize: '11px',
        color: 'rgba(255, 255, 255, 0.55)',
    },
    chartGridLine: {
        position: 'absolute',
        left: '30px',
        right: 0,
        height: '1px',
        background: 'rgba(255, 255, 255, 0.05)',
    },
    svgLineChart: {
        width: '100%',
        height: '100%',
        overflow: 'visible',
    },
    xAxis: {
        position: 'absolute',
        bottom: 0,
        left: '30px',
        right: 0,
        display: 'flex',
        justifyContent: 'space-between',
        fontSize: '11px',
        color: 'rgba(255, 255, 255, 0.55)',
    },
    donutContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '220px',
        position: 'relative',
    },
    donut: {
        width: '140px',
        height: '140px',
        borderRadius: '50%',
        background: `conic-gradient(
      #FFFFFF 0% 45%,
      rgba(255,255,255,0.4) 45% 75%,
      rgba(255,255,255,0.15) 75% 100%
    )`,
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    donutInner: {
        position: 'absolute',
        width: '110px',
        height: '110px',
        background: 'rgba(30, 30, 32, 0.45)',
        borderRadius: '50%',
        backdropFilter: 'blur(40px)',
        WebkitBackdropFilter: 'blur(40px)',
        boxShadow: 'inset 0 2px 10px rgba(0,0,0,0.2)',
    },
    donutCenterText: {
        position: 'absolute',
        textAlign: 'center',
        zIndex: 2,
    },
    donutTotal: {
        fontSize: '20px',
        fontWeight: 600,
        letterSpacing: '-0.5px',
    },
    donutLabel: {
        fontSize: '11px',
        color: 'rgba(255, 255, 255, 0.55)',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
        marginTop: '2px',
    },
    donutLegend: {
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: '12px',
        marginTop: '20px',
        width: '100%',
    },
    legendItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: '12px',
        color: 'rgba(255, 255, 255, 0.55)',
    },
    dot: {
        width: '8px',
        height: '8px',
        borderRadius: '50%',
    },
    bottomRow: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '20px',
        paddingBottom: '20px',
    },
    transactionList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    transactionItem: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '12px',
        borderRadius: '14px',
        background: 'rgba(255, 255, 255, 0.03)',
        transition: 'background 0.2s',
        cursor: 'pointer',
    },
    txLeft: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
    },
    txIcon: {
        width: '40px',
        height: '40px',
        borderRadius: '10px',
        background: 'rgba(255, 255, 255, 0.08)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        border: '1px solid rgba(255,255,255,0.05)',
    },
    txDetails: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    txTitle: {
        fontSize: '14px',
        fontWeight: 500,
    },
    txDate: {
        fontSize: '12px',
        color: 'rgba(255, 255, 255, 0.55)',
    },
    txAmount: {
        fontSize: '15px',
        fontWeight: 500,
        textAlign: 'right',
    },
    txCategory: {
        fontSize: '12px',
        color: 'rgba(255, 255, 255, 0.55)',
        textAlign: 'right',
        marginTop: '4px',
    },
    budgetList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        marginTop: '10px',
    },
    budgetItem: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
    },
    budgetHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    budgetTitle: {
        fontSize: '14px',
        fontWeight: 500,
    },
    budgetAmounts: {
        fontSize: '13px',
        color: 'rgba(255, 255, 255, 0.55)',
    },
    progressTrack: {
        height: '6px',
        borderRadius: '3px',
        background: 'rgba(255, 255, 255, 0.1)',
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        background: '#FFFFFF',
        borderRadius: '3px',
    },
    progressFillWarning: {
        height: '100%',
        background: '#FF9F0A',
        borderRadius: '3px',
    },
    progressFillDanger: {
        height: '100%',
        background: '#FF453A',
        borderRadius: '3px',
    },
};

export default customStyles